Feature do consumo de api, ordenação em lista e padrão strategy
Orderize/backoffice-api pull request #1
Opened 2024-08-31 21:29 UTC by Sant-Thiago

Essa branch contêm padrão strategy implementado contendo uma interface Olist e classes que a implementam; Contêm também consumo de api externa com openfeign e utiliza selectionSort para ordenar os objetos consumidos.

2024-09-06 23:57 UTC, GabrielRodAmaral commented on orderize/src/main/java/com/eight/group/projetct/orderize/Pizza/DTO/PizzaDTOResponse.java
Invés de instanciar uma nova Pizza e ir dando set poderia ter usado um construtor na Pizza para criar a nova no próprio return

2024-09-06 23:58 UTC, GabrielRodAmaral commented on orderize/src/main/resources/application.properties
Vai dar conflito.

2024-09-07 00:34 UTC, GabrielRodAmaral requested changes
Acredito que alguns dos comentário não vão ser muito úteis pra essa tarefa, porque conforme comentamos no zap, essa tarefa não vai ser mergeada na main, ela só serve pra essa apresentação. Mas servem para que em próximas tarefas a gente já tenha estabelecido os padrões e práticas.

2024-09-07 00:34 UTC, GabrielRodAmaral commented on orderize/src/main/java/com/eight/group/projetct/orderize/Pizza/DTO/PizzaDTOResponse.java
Acho que poderia alterar o nome dos Dto para ficar padronizado com o que já está no projeto

2024-09-07 00:34 UTC, GabrielRodAmaral commented on orderize/src/main/java/com/eight/group/projetct/orderize/Pizza/PizzaController.java
Acho melhor padronizarmos aquela questão que eu tinha falado no discord de utilizar construtor invés de Autowired

2024-09-07 00:34 UTC, GabrielRodAmaral commented on orderize/src/main/java/com/eight/group/projetct/orderize/external/Spoonacular/DTO/SpoonacularDTORecipe.java
Porque esse toPizza sem passar as propriedaes? Inclusive acho melhor utilizarmos o padrão de mapper para converter Dtos

2024-09-07 00:34 UTC, GabrielRodAmaral commented on orderize/src/main/java/com/eight/group/projetct/orderize/utils/OList.java
Porque essa classe é necessária?

2024-09-07 00:34 UTC, GabrielRodAmaral commented on orderize/src/main/java/com/eight/group/projetct/orderize/utils/IList.java
Por que essa interface é necessária?

2024-09-07 00:34 UTC, GabrielRodAmaral commented on orderize/src/main/java/com/eight/group/projetct/orderize/Pizza/DTO/PizzaDTOResponse.java
Atualmente o projeto possui mappers, melhor seguir o padrão porque deixa a manutenção do código mais fácil e fluida

2024-09-07 00:34 UTC, GabrielRodAmaral commented on orderize/src/main/java/com/eight/group/projetct/orderize/SecurityConfig.java
Esse arquivo pode ser excluido

2024-09-07 00:34 UTC, GabrielRodAmaral commented on orderize/src/main/java/com/eight/group/projetct/orderize/OrderizeApplication.java
Acredito que o nome do projeto está diferente, vai dar conflito

2024-09-07 00:50 UTC, Sant-Thiago commented on orderize/src/main/java/com/eight/group/projetct/orderize/utils/IList.java
A principio essa interface contem os métodos de listas como sort, search, entre outros, nesse contexto utilizo somente esse dois sort e search. Outras classes listas, como PizzaList utilizam esses métodos devido a herança.

2024-09-07 00:52 UTC, Sant-Thiago commented on orderize/src/main/java/com/eight/group/projetct/orderize/utils/OList.java
Essa classe é a classe que define o que um lista deveria fazer, nela já tem os métodos básicos de listas, ela implementa os métodos de organização e busca na lista do IList, e é utilizada nas classes listas como PizzaList

2024-10-09 03:05 UTC, closed without merging