criação do crud de Pedido e testes unitários
Orderize/backoffice-api pull request #14
Opened 2024-10-13 00:18 UTC by ju-camargo

2024-10-14 16:05 UTC, GabrielRodAmaral requested changes

2024-10-14 16:05 UTC, GabrielRodAmaral commented on src/main/java/com/orderize/backoffice_api/model/Order.java
Acredito que faltam algumas informações necessárias no pedido. Como os itens envolvidos no pedido e o preço bruto e líquido do pedido (na maioria dos casos serão o mesmo, mas em alguns pode ter algum desconto, seja por promoções ou por darem o desconto por outro motivo mesmo, o usuário tem que ter essa opção);

A classe possui construtores redundantes, 2 construtores vazios e 2 construtores com todas as propriedades;

Qual a necessidade de um construtor sem o cliente e o responsável?

2024-10-14 16:05 UTC, GabrielRodAmaral commented on src/main/java/com/orderize/backoffice_api/model/User.java
Por que a necessidade de adicionar essa propriedade no User?

2024-10-14 16:05 UTC, GabrielRodAmaral commented on src/main/resources/db/migration/V8__create_table_order.sql
Por que o frete double e o estimated_time decimal com 2 casas decimais? Não seria ao contrário?

2024-10-14 16:05 UTC, GabrielRodAmaral commented on src/main/java/com/orderize/backoffice_api/service/OrderService.java
Nos temos uma exceção criada no projeto para quando um recurso não é encontrado, é melhor lançar essa exceção que temos passando a mensagem do que fazer isso (ResponseStatusException(HttpStatus.NOT_FOUND)););

Não esta errado por essencia mas como no projeto não usamos em nenhum lugar não vejo porque colocar @Transactional nos métodos dessa service;

2024-10-14 16:05 UTC, GabrielRodAmaral commented on src/main/java/com/orderize/backoffice_api/dto/order/OrderResponseDto.java
Os dtos provavelmente também serão refatorados quando adicionar as propriedades citadas na Order

2024-10-14 16:05 UTC, GabrielRodAmaral commented on src/main/java/com/orderize/backoffice_api/controller/OrderController.java
O put não pode retornar 201, porque 201 é criada e ele só atualiza então melhor retornar 200 e não precisa de um response not found porque caso não seja encontrado a service precisa lançar a exceção que já existe no projeto ResourceNotFoundException com uma mensagem para que seja tratada pelo handler de exceptions;

2024-10-14 18:42 UTC, ju-camargo commented on src/main/java/com/orderize/backoffice_api/service/OrderService.java
certo. coloquei o @Transactional mesmo sabendo que não tinha no resto do projeto, a fim de levantar o questionamento sobre não ter e portanto, adicionar.

2024-10-14 18:44 UTC, ju-camargo commented on src/main/java/com/orderize/backoffice_api/model/Order.java
sobre o construtor sem cliente e responsável eu tinha criado para os testes unitários. mas já arrumei e deixei somente um construtor cheio e um vazio na classe.

2024-10-15 22:46 UTC, GabrielRodAmaral requested changes

2024-10-15 22:46 UTC, GabrielRodAmaral commented on src/main/java/com/orderize/backoffice_api/model/Order.java
Acredito que ainda tem aquela mesma questão dos itens envolvidos no pedido, isso pode ser algo que o front passa no request, e o Back tem que criar os preços brutos e líquidos com base nos itens do pedido e promoções aplicadas;

Também faltam os campos de preço e talz

2024-10-15 22:46 UTC, GabrielRodAmaral commented on src/main/java/com/orderize/backoffice_api/service/OrderService.java
Como eu disse no comentário na Order, o front tem que passar os pedidos e talz, e na hora de salvar a order deve ser calculado o preço pelo back

2024-10-17 01:07 UTC, GabrielRodAmaral commented on src/main/resources/db/migration/V8__create_table_order.sql
Vai dar conflito, porque já temos na develop V8, V9 e V10, faz essa migration ser V11 pfv

2024-10-17 01:08 UTC, GabrielRodAmaral commented on src/main/resources/db/migration/V8__create_table_order.sql
Na real esse pode ser V10, sorry

2024-10-28 13:43 UTC, closed without merging